 spring:
    datasource:
       url: jdbc:db2://123.123.123:55000/dsn01d
       username: Test
       password: Test
       driver-class-name: com.ibm.db2.jcc.DB2Driver
    jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.DB2Dialect
